In [4]:
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.optimizers import SGD, RMSprop, Adam
from matplotlib import pyplot as plt
import numpy as np
import time 

In [7]:
inputs = tf.linspace(0,10,4)
print(inputs)
b_2 = tf.ones([4,])
batch = tf.shape(inputs)[0]
b = tf.ones([batch,1])*b_2
start = time.time()
filas, columnas = tf.unstack(tf.shape(b))
#filas, columnas = b.shape
base = tf.identity(b)  # Creamos una copia del tensor original
print(base)
for i in range(filas):
    for j in range(columnas):
        base = tf.tensor_scatter_nd_update(base,
                                            [[i, j]],
                                            [tf.pow(inputs[i], j)])
print(base)
final = time.time() - start
print(final)

tf.Tensor([ 0.          3.33333333  6.66666667 10.        ], shape=(4,), dtype=float64)
tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[   1.           0.           0.           0.       ]
 [   1.           3.3333333   11.111111    37.037037 ]
 [   1.           6.6666665   44.444443   296.2963   ]
 [   1.          10.         100.        1000.       ]], shape=(4, 4), dtype=float32)
0.31581902503967285


In [6]:
inputs = tf.linspace(0,10,4)
print(inputs)
b_2 = tf.ones([4,])
batch = tf.shape(inputs)[0]
b = tf.ones([batch,1])*b_2
start = time.time()
#filas, columnas = tf.unstack(tf.shape(b))
filas, columnas = b.shape
base = tf.identity(b)  # Creamos una copia del tensor original
print(base)
for i in range(filas):
    for j in range(columnas):
        base = tf.tensor_scatter_nd_update(base,
                                            [[i, j]],
                                            [tf.pow(inputs[i], j)])
print(base)
final = time.time() - start
print(final)

tf.Tensor([ 0.          3.33333333  6.66666667 10.        ], shape=(4,), dtype=float64)
tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[   1.           0.           0.           0.       ]
 [   1.           3.3333333   11.111111    37.037037 ]
 [   1.           6.6666665   44.444443   296.2963   ]
 [   1.          10.         100.        1000.       ]], shape=(4, 4), dtype=float32)
0.37200927734375
